events {}

http {
  server {
    listen 3000 ssl;

    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    client_max_body_size 40m;

    location / {
      proxy_pass http://web:3000;
      proxy_set_header Host localhost;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
